// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izcygzivclegpkolbkjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Y3lneml2Y2xlZ3Brb2xia2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTgxNTYsImV4cCI6MjA2NzIzNDE1Nn0.nM6lohGMuAE0r3siFo27waOKtry9-X_YvW-P-ML7g_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});